# Generated by Django 3.0.8 on 2020-07-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=100, verbose_name="Owner's id")),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('option1', models.CharField(max_length=25, verbose_name='1_st option')),
                ('option2', models.CharField(max_length=25, verbose_name='2_nd option')),
                ('option3', models.CharField(max_length=25, verbose_name='3_d option')),
                ('votes1', models.IntegerField(default=0, max_length=300, verbose_name='1_st votes')),
                ('votes2', models.IntegerField(default=0, max_length=300, verbose_name='2_nd votes')),
                ('votes3', models.IntegerField(default=0, max_length=300, verbose_name='3_d votes')),
                ('total', models.IntegerField(default=0, max_length=300, verbose_name='total_votes')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
            },
        ),
    ]
